### ISSUE TITLE
VPN Disconnecting Intermittently on Windows devices

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#354]
This is a sister ticket to #346

**Comment by sregister** [comment]
I'm running windows 10 build 15063.13 in the insider preview slow ring which should be very close to the final build of creators update and still having issues. Disabling mobile and adding the registry entry seemed to work for a while but after a system restart it started happening again.

**Comment by dmatta22201** [comment]
Had the same issue on Windows 10 after using default settings to create a t2.micro server on AWS. Noticed even when the VPN died, I was still maintaining my SSH connection to the server. Changed the IPv4 connection properties to specify OpenDNS servers for DNS services. Also disabled mobility. Since then, it has been running without issue. Will post back in a few days with an update.

**Comment by Steve9F** [comment]
Running final release of the creators update and experiencing the same disconnect issue. Haven't tried any of the proposed fixes as yet.

**Comment by brianytang** [comment]
@dguido Any update on this? I've been getting disconnects on win 10 (creators edition) using azure as well as digital ocean. Is disabling DPD from the other ticket related to this?

**Comment by dguido** [comment]
We do our best to keep all the Issues up to date. I'm not hiding anything! If there are no updates on the Issue, then there are probably no updates.

I don't use Windows and neither does anyone else on the core development team. If you have an issue with Windows, we're counting on you to contribute time to help diagnose the issue.

**Comment by bshiznit** [comment]
I will help - for me the disconnect is 57 minutes for whatever reason -
every time regardless of GC2, DO or GCE - so I think it is
re-authenticating or something at that interval. I will begin scouring logs
and get back - Windows 10 and Ubuntu/Charon/systemd (guess I could use some
StringSwan log scouring tips)... It, too, am on creator's update.

Thanks Dan

**Comment by Steve9F** [comment]
I don’t have detailed technical experience with VPN but am happy to help run tests. My server is running on EC2 and I have three W10 creators update systems configured. I can also configure on W10 anniversary systems if needed.

**Comment by bshiznit** [comment]
As I suspected - lease expiring (note I obfuscated my IP):

`10[NET] sending packet: from 172.16.254.35[4500] to 00.0.000.000[4500]
02[MGR] checkout IKE_SA
02[MGR] IKE_SA ikev2-pubkey[1] successfully checked out
02[IKE] sending keep alive to 00.0.000.000[4500]
02[MGR] checkin IKE_SA ikev2-pubkey[1]
02[MGR] check-in of IKE_SA successful.
10[NET] sending packet: from 172.16.254.35[4500] to 00.0.000.000[4500]
00[DMN] signal of type SIGINT received. Shutting down
00[MGR] going to destroy IKE_SA manager and all managed IKE_SA's
00[MGR] set driveout flags for all stored IKE_SA's
00[MGR] wait for all threads to leave IKE_SA's
00[MGR] delete all IKE_SA's
00[IKE] queueing IKE_DELETE task
00[IKE] activating new tasks
00[IKE]   activating IKE_DELETE task
00[IKE] deleting IKE_SA ikev2-pubkey[1] between 172.16.254.35[13.58.46.72]...00.0.000.000[CN=bshiznit]
00[IKE] IKE_SA ikev2-pubkey[1] state change: ESTABLISHED => DELETING
00[IKE] sending DELETE for IKE_SA ikev2-pubkey[1]
00[ENC] generating INFORMATIONAL request 0 [ D ]
00[NET] sending packet: from 172.16.254.35[4500] to 00.0.000.000[4500] (80 bytes)
00[MGR] destroy all entries
00[IKE] IKE_SA ikev2-pubkey[1] state change: DELETING => DESTROYING
00[CFG] lease fd9d:bc11:4020::1 by 'CN=bshiznit' went offline
00[CFG] lease 10.19.48.1 by 'CN=bshiznit' went offline
10[NET] sending packet: from 172.16.254.35[4500] to 00.0.000.000[4500]`

**Comment by dguido** [comment]
Thanks! That's progress. At least we know one source of the issue now.

**Comment by bshiznit** [comment]
OK some more info! I don't know much about this - but at some point around the 57 minute mark my Windows 10 Creator's Update client can no longer checkout CHILD_SA? At this point the tunnel remains connected - but no further packets are received - they are sent though... I must manually disconnect and reconnect at this point or it will stay in this stay indefinitely...

Here is around that 57 minute mark:
10[MGR] checkout IKEv2 SA with SPIs ab0704a90459091f_i 812ef48fc7c5b590_r
10[MGR] IKE_SA ikev2-pubkey[1] successfully checked out
10[KNL] querying policy 0.0.0.0/0 === 10.19.48.1/32 out
10[KNL] querying policy ::/0 === fd9d:bc11:4020::1/128 out
10[MGR] checkin IKE_SA ikev2-pubkey[1]
10[MGR] checkin of IKE_SA successful
03[NET] received packet: from <MYIP>[4500] to 10.128.0.3[4500]
03[NET] waiting for data on sockets
11[MGR] checkout IKEv2 SA by message with SPIs ab0704a90459091f_i 812ef48fc7c5b590_r
11[MGR] IKE_SA ikev2-pubkey[1] successfully checked out
11[NET] received packet: from <MYIP>[4500] to 10.128.0.3[4500] (312 bytes)
11[ENC] parsed CREATE_CHILD_SA request 2 [ N(REKEY_SA) SA No TSi TSr ]
11[CFG] selecting proposal:
11[CFG]   no acceptable DIFFIE_HELLMAN_GROUP found
11[CFG] selecting proposal:
11[CFG]   no acceptable ENCRYPTION_ALGORITHM found
11[CFG] received proposals: ESP:AES_GCM_16_128/NO_EXT_SEQ
11[CFG] configured proposals: ESP:AES_GCM_16_128/ECP_256/NO_EXT_SEQ, ESP:AES_CBC_128/HMAC_SHA2_512_256/ECP_256/NO_EXT_SEQ
11[IKE] no acceptable proposal found
11[IKE] failed to establish CHILD_SA, keeping IKE_SA
11[ENC] generating CREATE_CHILD_SA response 2 [ N(NO_PROP) ]
11[NET] sending packet: from 10.128.0.3[4500] to <MYIP>[4500] (88 bytes)
11[MGR] checkin IKE_SA ikev2-pubkey[1]
11[MGR] checkin of IKE_SA successful
04[NET] sending packet: from 10.128.0.3[4500] to <MYIP>[4500]

A bit later as it continues to fail CREATE_CHILD_SA - DPD?
12[MGR] checkout IKEv2 SA with SPIs ab0704a90459091f_i 812ef48fc7c5b590_r
12[MGR] IKE_SA ikev2-pubkey[1] successfully checked out
12[IKE] sending keep alive to <MYIP>[4500]
12[MGR] checkin IKE_SA ikev2-pubkey[1]
12[MGR] checkin of IKE_SA successful
04[NET] sending packet: from 10.128.0.3[4500] to <MYIP>[4500]
13[MGR] checkout IKEv2 SA with SPIs ab0704a90459091f_i 812ef48fc7c5b590_r
13[MGR] IKE_SA ikev2-pubkey[1] successfully checked out
13[MGR] checkin IKE_SA ikev2-pubkey[1]
13[MGR] checkin of IKE_SA successful
14[MGR] checkout IKEv2 SA with SPIs ab0704a90459091f_i 812ef48fc7c5b590_r
14[MGR] IKE_SA ikev2-pubkey[1] successfully checked out
14[IKE] sending DPD request
14[IKE] queueing IKE_DPD task
14[IKE] activating new tasks
14[IKE]   activating IKE_DPD task

And finally when I decide to click disconnect:
16[MGR] checkout IKEv2 SA by message with SPIs ab0704a90459091f_i 812ef48fc7c5b590_r
16[MGR] IKE_SA ikev2-pubkey[1] successfully checked out
16[NET] received packet: from <MYIP>[4500] to 10.128.0.3[4500] (88 bytes)
16[ENC] parsed INFORMATIONAL request 6 [ D ]
16[IKE] received DELETE for IKE_SA ikev2-pubkey[1]
16[IKE] deleting IKE_SA ikev2-pubkey[1] between 10.128.0.3[146.148.69.119]...<MYIP>[CN=bshiznit]
16[IKE] IKE_SA ikev2-pubkey[1] state change: ESTABLISHED => DELETING
16[IKE] IKE_SA deleted
16[ENC] generating INFORMATIONAL response 6 [ ]
16[NET] sending packet: from 10.128.0.3[4500] to <MYIP>[4500] (88 bytes)
16[MGR] checkin and destroy IKE_SA ikev2-pubkey[1]
16[IKE] IKE_SA ikev2-pubkey[1] state change: DELETING => DESTROYING
16[CFG] lease fd9d:bc11:4020::1 by 'CN=bshiznit' went offline
16[CFG] lease 10.19.48.1 by 'CN=bshiznit' went offline
16[MGR] checkin and destroy of IKE_SA successful
04[NET] sending packet: from 10.128.0.3[4500] to <MYIP>[4500]
05[MGR] checkout IKEv2 SA with SPIs ab0704a90459091f_i 812ef48fc7c5b590_r
05[MGR] IKE_SA checkout not successful
07[MGR] checkout IKEv2 SA with SPIs ab0704a90459091f_i 812ef48fc7c5b590_r
07[MGR] IKE_SA checkout not successful
06[MGR] checkout IKEv2 SA

[algodisconnectlogs.zip](https://github.com/trailofbits/algo/files/952552/algodisconnectlogs.zip)

I also attached the full ipsec log - and a tracing log from my Win10 client! Let me know if anything else I can do!

**Comment by bshiznit** [comment]
OK well this fixed me up on my Windows 10 client - no more broken tunnel around the 57 minute mark - reconfigured my connection using PowerShell with -PfsGroup ECP256

Is that a valid fix? Happy to submit a PR... Now the log no longer indicates no acceptable proposal found:
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[ENC] parsed CREATE_CHILD_SA request 2 [ N(REKEY_SA) SA No TSi TSr KE ]
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[CFG] selecting proposal:
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[CFG]   proposal matches
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[CFG] received proposals: ESP:AES_GCM_16_128/ECP_256/NO_EXT_SEQ
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[CFG] configured proposals: ESP:AES_GCM_16_128/ECP_256/NO_EXT_SEQ, ESP:AES_CBC_128/HMAC_SHA2_512_256/ECP_256/NO_EXT_SEQ
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[CFG] selected proposal: ESP:AES_GCM_16_128/ECP_256/NO_EXT_SEQ
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[KNL] got SPI ca0c8891
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[CFG] selecting traffic selectors for us:
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[CFG]  config: 0.0.0.0/0, received: 0.0.0.0/0 => match: 0.0.0.0/0
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[CFG]  config: 0.0.0.0/0, received: ::/0 => no match
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[CFG]  config: ::/0, received: 0.0.0.0/0 => no match
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[CFG]  config: ::/0, received: ::/0 => match: ::/0
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[CFG] selecting traffic selectors for other:
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[CFG]  config: 10.19.48.1/32, received: 0.0.0.0/0 => match: 10.19.48.1/32
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[CFG]  config: 10.19.48.1/32, received: ::/0 => no match
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[CFG]  config: fd9d:bc11:4020::1/128, received: 0.0.0.0/0 => no match
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[CFG]  config: fd9d:bc11:4020::1/128, received: ::/0 => match: fd9d:bc11:4020::1/128
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[KNL] adding SAD entry with SPI ca0c8891 and reqid {2}
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[KNL]   using encryption algorithm AES_GCM_16 with key size 160
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[KNL]   using replay window of 32 packets
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[KNL] adding SAD entry with SPI 2a19f468 and reqid {2}
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[KNL]   using encryption algorithm AES_GCM_16 with key size 160
Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[KNL]   using replay window of 0 packets

**Comment by jauderho** [comment]
Interesting.

@dguido It looks like now GCM is being offered as a valid proposal.

`Apr 25 20:22:35 algo-gce-oh charon[21740]: 12[CFG] selected proposal: ESP:AES_GCM_16_128/ECP_256/NO_EXT_SEQ`

**Comment by dguido** [comment]
We know, we committed that a day or so ago.

**Comment by gunph1ld** [comment]
@bshiznit make some test with and without PfsGroup again and if it happens again send a PR, please.

**Comment by brianytang** [comment]
Can confirm adding -PfsGroup ECP256 to the end of the powershell script has been working wonders for the past 3 hours. Originally I was getting disconnected every 20-40 mins

**Comment by PhillippOhlandt** [comment]
Just tried it with `-PfsGroup ECP256`. It's still not working here.

**Comment by bshiznit** [comment]
@PhillippOhlandt - what's the full PowerShell command line?

**Comment by PhillippOhlandt** [comment]
@bshiznit 
```
certutil -f -p PASSWORD -importpfx .\USERNAME.p12
Add-VpnConnection -name "Algo VPN IP IKEv2" -ServerAddress "IP" -TunnelType IKEv2 -AuthenticationMethod MachineCertificate -EncryptionLevel Required
Set-VpnConnectionIPsecConfiguration -ConnectionName "Algo VPN IP IKEv2" -AuthenticationTransformConstants SHA256128 -CipherTransformConstants AES128 -EncryptionMethod AES128 -IntegrityCheckMethod SHA256 -DHGroup Group14 -PfsGroup ECP256
```

(censored ip, username and password)

**Comment by bshiznit** [comment]
OK - the default compat ciphers were changed a few days ago - my command looks like:
`Set-VpnConnectionIPsecConfiguration -ConnectionName "<NAME>" -AuthenticationTransformConstants GCMAES128 -CipherTransformConstants GCMAES128 -EncryptionMethod AES128 -IntegrityCheckMethod SHA384 -DHGroup ECP256 -PfsGroup ECP256`

Which is the current cipher suite merged into master 2 days ago... Update algo, redeploy and re-test if you are able...

**Comment by tuangd** [comment]
I updated Algo tonight and trying the new script. Seems like it's working.

**Comment by PhillippOhlandt** [comment]
@bshiznit I deployed a new server using the current master branch + the `-PfsGroup ECP256` parameter in the script. It's working fine since 2,5h now. Seems like it's finally solved.

**Comment by Steve9F** [comment]
Confirming that I updated and redeployed with the -PfsGroup ECP256 parameter and now everything is working fine. Connection has been up and running for 15 hours as I type this. Thank you all for your work on this.

**Comment by bshiznit** [comment]
FYI I am looking deeper into enabling new ciphers in Win10 1703:
https://technet.microsoft.com/en-us/itpro/powershell/windows/tls/enable-tlsciphersuite

@dguido I do NOT think SHA2-512 will be supported... Soon...

As well as possibilities of using XML file profiles for setting up the VPN connection...

**Comment by dguido** [comment]
Thanks! If it's possible to use an XML file to auto setup Windows VPNs, please file a ticket for it.

**Comment by gunph1ld** [comment]
We can close this for now I guess
